# Configuration properties for the test framework
default.timeout=10000
short.timeout=3000
long.timeout=30000
# Application URLs
base.url=https://ecommerce-playground.lambdatest.io/
api.base.url=
ws.url=
# AI API Keys
OPENAI_API_KEY=
GEMINI_API_KEY=AIzaSyCbptLM6iysoEHEfxyvdUErsC8CW9QVNgo
CLAUDE_API_KEY=
# AI Models
OPENAI_MODEL=
GEMINI_MODEL=gemini-2.5-flash
CLAUDE_MODEL=
# Urls for AI APIs
CLAUDE_MESSAGES_URL = https://api.anthropic.com/v1/messages
GEMINI_BASE_URL = https://generativelanguage.googleapis.com/v1beta/models/%s:generateContent?key=%s
OPENAI_RESPONSES_URL = https://api.openai.com/v1/responses
# Claude version for compatibility
ANTHROPIC_VERSION = 2023-06-01