default.timeout=10000
short.timeout=3000
long.timeout=30000

base.url=https://ecommerce-playground.lambdatest.io/
api.base.url=
ws.url=

# AI API Keys
OPENAI_API_KEY=
GEMINI_API_KEY=AIzaSyCbptLM6iysoEHEfxyvdUErsC8CW9QVNgo
CLAUDE_API_KEY=
# AI Models
OPENAI_MODEL=
GEMINI_MODEL=gemini-2.5-flash
CLAUDE_MODEL=