# Activer l'exécution en parallèle
junit.jupiter.execution.parallel.enabled = true
# Mode "concurrent" pour les classes et les méthodes
junit.jupiter.execution.parallel.mode.default = concurrent
junit.jupiter.execution.parallel.mode.classes.default = concurrent
# Configuration du nombre de threads (ex: 4 tests en même temps)
junit.jupiter.execution.parallel.config.strategy = fixed
junit.jupiter.execution.parallel.config.fixed.parallelism = 4
# Dit à Cucumber de traiter chaque scénario comme une unité indépendante
cucumber.execution.parallel.enabled = true
cucumber.glue=stepdefinitions/api,stepdefinitions/ui,stepdefinitions/hybrid,stepdefinitions/websocket,hooks
