# Activer l'exécution en parallèle
junit.jupiter.execution.parallel.enabled = true

# Mode "concurrent" pour les classes et les méthodes
junit.jupiter.execution.parallel.mode.default = concurrent
junit.jupiter.execution.parallel.mode.classes.default = concurrent

# Configuration du nombre de threads (ex: 4 tests en même temps)
junit.jupiter.execution.parallel.config.strategy = fixed
junit.jupiter.execution.parallel.config.fixed.parallelism = 4

# Cucumber configuration
cucumber.execution.parallel.enabled = true
cucumber.glue=stepdefinitions.api,stepdefinitions.ui,stepdefinitions.hybrid,stepdefinitions.websocket,hooks
cucumber.plugin = pretty, io.qameta.allure.cucumber7jvm.AllureCucumber7Jvm
cucumber.execution.dry-run = false
cucumber.filter.tags = not @ignore
cucumber.ansi.colors.enabled = false