#Locators for the Home page
btn_my_account=css|body > div:nth-child(1) > div:nth-child(5) > header:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > nav:nth-child(1) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(6) > a:nth-child(1)
#Locators for the Login page
txt_email=role|textbox|E-Mail Address;css|#input-email;css|input[name='email']
txt_password=css|input[id*='password'];label|Password-pwd
btn_login=role|button|Login;css|input.btn.btn-primary