pipeline {
    agent any

    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '10'))
        disableConcurrentBuilds()
        timeout(time: 60, unit: 'MINUTES')
    }

    parameters {
        choice(
            name: 'BROWSER',
            choices: ['chromium'],
            description: 'Browser used by Playwright'
        )

        string(
            name: 'CUCUMBER_TAGS',
            defaultValue: ['@ui', '@api' , '@ws' ,'@hybrid'],
            description: 'Cucumber tags to execute'
        )

        string(
            name: 'CUCUMBER_TAGS',
            choice: ['','@ui', '@api' , '@ws' ,'@hybrid'],
            description: 'Optional Cucumber tag. Empty = run all scenarios except @ignore. Example: @ui, @api, @websocket, @ui or @api'
        )

        choice(
            name: 'FRAMEWORK_LOG_LEVEL',
            choices: ['INFO', 'DEBUG', 'WARN', 'ERROR'],
            description: 'Framework log level'
        )
    }

    environment {
        ALLURE_RESULTS = 'target/allure-results'
        ALLURE_REPORT = 'allure-report'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Tools') {
            steps {
                sh '''
                    echo "Checking Java..."
                    java -version

                    echo "Checking Maven..."
                    mvn -version

                    echo "Checking Allure..."
                    allure --version || true
                '''
            }
        }

        stage('Prepare Workspace') {
            steps {
                sh '''
                    mkdir -p target/logs
                    mkdir -p target/videos
                    mkdir -p target/allure-results
                '''
            }
        }

        stage('Install Playwright Browser') {
            steps {
                sh """
                    mvn -q exec:java \
                      -Dexec.mainClass=com.microsoft.playwright.CLI \
                      -Dexec.args="install ${params.BROWSER}"
                """
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    def userTags = params.CUCUMBER_TAGS?.trim()
                    def finalTags = ''

                    if (userTags == null || userTags == '') {
                        finalTags = 'not @ignore'
                    } else {
                        finalTags = "(${userTags}) and not @ignore"
                    }

                    echo "Final Cucumber tags: ${finalTags}"

                    sh """
                        mvn clean test \
                          -Denv=${params.ENV} \
                          -Dbrowser.name=${params.BROWSER} \
                          -Dframework.log.level=${params.FRAMEWORK_LOG_LEVEL} \
                          -Dlibrary.log.level=WARN \
                          -Dcucumber.filter.tags="${finalTags}"
                    """
                }
            }
        }

        stage('Prepare Allure History') {
            steps {
                sh '''
                    if [ -d "${ALLURE_REPORT}/history" ]; then
                        mkdir -p "${ALLURE_RESULTS}/history"
                        cp -r "${ALLURE_REPORT}/history/"* "${ALLURE_RESULTS}/history/" || true
                    else
                        echo "No previous Allure history found."
                    fi
                '''
            }
        }

        stage('Generate Allure Report') {
            steps {
                sh '''
                    allure generate "${ALLURE_RESULTS}" --clean -o "${ALLURE_REPORT}" || true
                '''
            }
        }
    }

    post {
        always {
            echo 'Publishing reports and archiving artifacts...'

            junit allowEmptyResults: true, testResults: 'target/surefire-reports/*.xml'

            archiveArtifacts artifacts: '''
                target/allure-results/**,
                allure-report/**,
                target/logs/**,
                target/videos/**
            ''', allowEmptyArchive: true

            allure([
                includeProperties: false,
                jdk: '',
                reportBuildPolicy: 'ALWAYS',
                results: [[path: 'target/allure-results']]
            ])
        }

        success {
            echo 'Pipeline completed successfully.'
        }

        failure {
            echo 'Pipeline failed.'
        }
    }
}