#Locators for the Login page
txt_email=css|#input-email;role|textbox|E-Mail Address;css|input[name='email']
txt_password=css|input[name='password'];label|Password-pwd
btn_login=role|button|Login;css|input.btn.btn-primary


